"""username

Revision ID: 7d29726db9fd
Revises: d68ab7f4a793
Create Date: 2023-01-22 21:31:22.073497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d29726db9fd'
down_revision = 'd68ab7f4a793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.drop_index('ix_message_board_mb_username')
        batch_op.create_index(batch_op.f('ix_message_board_mb_username'), ['mb_username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_board_mb_username'))
        batch_op.create_index('ix_message_board_mb_username', ['mb_username'], unique=False)

    # ### end Alembic commands ###
