"""DB init

Revision ID: 84771ac81a9b
Revises: 7d29726db9fd
Create Date: 2023-01-24 18:15:53.698260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84771ac81a9b'
down_revision = '7d29726db9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('regist_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('regist_date')
        batch_op.drop_column('location')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
