"""add

Revision ID: 980ddbbd3d9b
Revises: 84771ac81a9b
Create Date: 2023-01-25 01:46:45.288476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980ddbbd3d9b'
down_revision = '84771ac81a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
