"""addtable

Revision ID: d68ab7f4a793
Revises: 
Create Date: 2023-01-22 21:14:38.474276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68ab7f4a793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mb_data', sa.DateTime(), nullable=True))
        batch_op.alter_column('mb_message',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.alter_column('mb_message',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('mb_data')

    # ### end Alembic commands ###
